<?php
function quiz_theme($existing, $type, $theme, $path) {
  return array(	  	
	  	'quiz' => array(
	            			'variables' => array(	                		
	                						  'content' => 'from hook module',
	            							),
	            				),	
    );
}
/*
function rosenserien_custom_blocks_module_template_preprocess_default_variables_alter(&$variables) {
  $variables['title_arrow'] ='/' . drupal_get_path('module', 'storleden_module') . '/images/icon/heading-arrow.png';
}
*/